services:

  achievement_system:
    build: ./achievement-system
    container_name: achievement_system
    restart: always
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_started
        restart: true
    post_start:
      - command: php artisan migrate:fresh --seed

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MARIADB_DATABASE: achievement_system
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8001:8080
    depends_on:
      db:
        condition: service_started
        restart: true