services:

  achievement_system:
    build: ./achievement-system
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_started
        restart: true

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MARIADB_DATABASE: achievement_system
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_started
        restart: true